-- campaign.lua
-- Micro-trial campaign: short sharp rooms, hard cuts, one rule per room.
-- Inspired by WarioWare brevity + Blendo Games smash cuts + Dante's progressive loss.

return {
    id = "infernal_ascent",
    title = "INFERNAL ASCENT",
    subtitle = "Each circle strips a verb. Each trial proves the new rule.",
    rooms = {
        -- ============================================================
        -- LIMBO — Full kit. Learn the verbs. 5 micro-trials.
        -- ============================================================
        {
            id = "limbo_01",
            title = "LIMBO",
            subtitle = "Cross.",
            trial_rule = "REACH THE OTHER SIDE",
            mode = "campaign",
            room_type = "trial",
            circle_id = "limbo",
            hard_cut = true,
            completion = "reach_zone",
            reach_zone = { x = 36 * 32, y = 8 * 32, width = 32, height = 64 },
            trial_timer = 8,
            fragments_required = 0,
            show_gate = false,
            bg = { 0.1, 0.11, 0.14 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.88, 0.58, 0.24 },
            abilities = { shoot = true, grapple = true, dash = true },
            map = {
                "1111111111111111111111111111111111111111",
                "1                                      1",
                "1 P                                    1",
                "1 11                                   1",
                "1        111                           1",
                "1                  111                 1",
                "1                           111        1",
                "1                                      1",
                "1      1                          11   1",
                "1                                      1",
                "1111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_02",
            title = "LIMBO",
            subtitle = "Climb.",
            trial_rule = "WALL JUMP TO THE TOP",
            mode = "campaign",
            room_type = "trial",
            circle_id = "limbo",
            hard_cut = true,
            completion = "reach_zone",
            reach_zone = { x = 8 * 32, y = 1 * 32, width = 64, height = 32 },
            trial_timer = 10,
            fragments_required = 0,
            show_gate = false,
            bg = { 0.1, 0.11, 0.14 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.88, 0.58, 0.24 },
            abilities = { shoot = true, grapple = true, dash = true },
            map = {
                "111111111111111111",
                "1                1",
                "1                1",
                "1  1        1    1",
                "1  1        1    1",
                "1  1        1    1",
                "1       11       1",
                "1  1        1    1",
                "1  1        1    1",
                "1  1        1    1",
                "1       11       1",
                "1  1        1    1",
                "1  1     P  1    1",
                "1  1   111  1    1",
                "111111111111111111",
            },
        },
        {
            id = "limbo_03",
            title = "LIMBO",
            subtitle = "Shoot.",
            trial_rule = "KILL EVERYTHING",
            mode = "campaign",
            room_type = "trial",
            circle_id = "limbo",
            hard_cut = true,
            completion = "kill_all",
            trial_timer = 12,
            fragments_required = 0,
            show_gate = false,
            bg = { 0.1, 0.11, 0.14 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.88, 0.58, 0.24 },
            abilities = { shoot = true, grapple = true, dash = true },
            encounter_config = {
                trigger_x = 0,
                bounds = { left = 0, right = 24 * 32 },
                waves = {
                    {
                        spawns = {
                            { x = 14 * 32, y = 6 * 32, type = "walker" },
                            { x = 18 * 32, y = 6 * 32, type = "walker" },
                            { x = 16 * 32, y = 2 * 32, type = "harpy" },
                        },
                    },
                },
            },
            map = {
                "11111111111111111111111111",
                "1                        1",
                "1                        1",
                "1  P                     1",
                "1  11                    1",
                "1                        1",
                "1          1111    1111  1",
                "1                        1",
                "1                        1",
                "11111111111111111111111111",
            },
        },
        {
            id = "limbo_04",
            title = "LIMBO",
            subtitle = "Chain.",
            trial_rule = "GRAPPLE ACROSS THE PIT",
            mode = "campaign",
            room_type = "trial",
            circle_id = "limbo",
            hard_cut = true,
            completion = "reach_zone",
            reach_zone = { x = 28 * 32, y = 2 * 32, width = 32, height = 64 },
            trial_timer = 10,
            fragments_required = 0,
            show_gate = false,
            bg = { 0.1, 0.11, 0.14 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.88, 0.58, 0.24 },
            abilities = { shoot = true, grapple = true, dash = true },
            map = {
                "1111111111111111111111111111111",
                "1                             1",
                "1 P              A         A  1",
                "1 11                          1",
                "1        A                    1",
                "1                      11111  1",
                "1                             1",
                "1 222222222222222222222        1",
                "1111111111111111111111111111111",
            },
        },
        {
            id = "limbo_05",
            title = "LIMBO",
            subtitle = "Survive.",
            trial_rule = "STAY ALIVE",
            mode = "campaign",
            room_type = "trial",
            circle_id = "limbo",
            hard_cut = true,
            completion = "survive",
            trial_timer = 10,
            fragments_required = 0,
            show_gate = false,
            bg = { 0.12, 0.13, 0.17 },
            solid_color = { 0.3, 0.33, 0.38 },
            accent_color = { 0.92, 0.6, 0.26 },
            abilities = { shoot = true, grapple = true, dash = true },
            encounter_config = {
                trigger_x = 0,
                bounds = { left = 0, right = 20 * 32 },
                waves = {
                    {
                        spawns = {
                            { x = 14 * 32, y = 5 * 32, type = "walker" },
                            { x = 16 * 32, y = 2 * 32, type = "harpy" },
                        },
                        delay_after_clear = 0.3,
                    },
                    {
                        spawns = {
                            { x = 6 * 32, y = 5 * 32, type = "walker" },
                            { x = 14 * 32, y = 5 * 32, type = "walker" },
                            { x = 10 * 32, y = 2 * 32, type = "harpy" },
                        },
                    },
                },
            },
            map = {
                "11111111111111111111",
                "1                  1",
                "1  P               1",
                "1  11              1",
                "1                  1",
                "1       1111       1",
                "1                  1",
                "1  111        111  1",
                "11111111111111111111",
            },
        },

        -- ============================================================
        -- LUST — Grapple stripped. Wind replaces recovery. 5 micro-trials.
        -- ============================================================
        {
            id = "lust_01",
            title = "LUST",
            subtitle = "The chain is taken.",
            trial_rule = "NO GRAPPLE. CROSS.",
            mode = "campaign",
            room_type = "trial",
            circle_id = "lust",
            hard_cut = true,
            completion = "reach_zone",
            reach_zone = { x = 30 * 32, y = 6 * 32, width = 32, height = 64 },
            trial_timer = 10,
            removed_ability = "grapple",
            fragments_required = 0,
            show_gate = false,
            bg = { 0.2, 0.1, 0.16 },
            solid_color = { 0.4, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            abilities = { shoot = true, grapple = false, dash = true },
            map = {
                "11111111111111111111111111111111",
                "1                              1",
                "1 P                            1",
                "1 11                           1",
                "1         111                  1",
                "1                    111       1",
                "1                              1",
                "1                         11   1",
                "1  222222222222222222222        1",
                "11111111111111111111111111111111",
            },
        },
        {
            id = "lust_02",
            title = "LUST",
            subtitle = "Wind.",
            trial_rule = "RIDE THE TAILWIND",
            mode = "campaign",
            room_type = "trial",
            circle_id = "lust",
            hard_cut = true,
            completion = "reach_zone",
            reach_zone = { x = 34 * 32, y = 5 * 32, width = 32, height = 96 },
            trial_timer = 8,
            removed_ability = "grapple",
            fragments_required = 0,
            show_gate = false,
            bg = { 0.2, 0.1, 0.16 },
            solid_color = { 0.4, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            abilities = { shoot = true, grapple = false, dash = true },
            wind_areas = {
                {
                    x = 4 * 32, y = 1 * 32,
                    width = 28 * 32, height = 8 * 32,
                    force_x = 520,
                    label = "Tailwind",
                },
            },
            map = {
                "111111111111111111111111111111111111111",
                "1                                     1",
                "1 P                                   1",
                "1 11                                  1",
                "1                                     1",
                "1        11                    111    1",
                "1                                     1",
                "1              11         11          1",
                "1  22222222222222222222222222222       1",
                "111111111111111111111111111111111111111",
            },
        },
        {
            id = "lust_03",
            title = "LUST",
            subtitle = "Brace.",
            trial_rule = "CROUCH THROUGH THE GUST",
            mode = "campaign",
            room_type = "trial",
            circle_id = "lust",
            hard_cut = true,
            completion = "reach_zone",
            reach_zone = { x = 26 * 32, y = 7 * 32, width = 32, height = 64 },
            trial_timer = 10,
            removed_ability = "grapple",
            fragments_required = 0,
            show_gate = false,
            bg = { 0.2, 0.1, 0.16 },
            solid_color = { 0.4, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            abilities = { shoot = true, grapple = false, dash = true, crouch = true },
            wind_areas = {
                {
                    x = 6 * 32, y = 3 * 32,
                    width = 16 * 32, height = 6 * 32,
                    force_x = -600,
                    label = "Headwind",
                },
            },
            map = {
                "1111111111111111111111111111111",
                "1                             1",
                "1                             1",
                "1 P                           1",
                "1 11                          1",
                "1                             1",
                "1                             1",
                "1                             1",
                "1111111111111111111111111  111 1",
                "1111111111111111111111111111111",
            },
        },
        {
            id = "lust_04",
            title = "LUST",
            subtitle = "Bank.",
            trial_rule = "RICOCHET KILL IN CROSSWIND",
            mode = "campaign",
            room_type = "trial",
            circle_id = "lust",
            hard_cut = true,
            completion = "kill_all",
            trial_timer = 12,
            removed_ability = "grapple",
            fragments_required = 0,
            show_gate = false,
            bg = { 0.22, 0.1, 0.17 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            abilities = { shoot = true, grapple = false, dash = true },
            wind_areas = {
                {
                    x = 6 * 32, y = 1 * 32,
                    width = 12 * 32, height = 8 * 32,
                    force_x = -350,
                    label = "Crosswind",
                },
            },
            encounter_config = {
                trigger_x = 0,
                bounds = { left = 0, right = 24 * 32 },
                waves = {
                    {
                        spawns = {
                            { x = 18 * 32, y = 4 * 32, type = "walker" },
                            { x = 20 * 32, y = 2 * 32, type = "harpy" },
                        },
                    },
                },
            },
            map = {
                "11111111111111111111111111",
                "1                        1",
                "1  P                     1",
                "1  11                    1",
                "1              1111      1",
                "1                        1",
                "1        1111            1",
                "1                        1",
                "11111111111111111111111111",
            },
        },
        {
            id = "lust_05",
            title = "LUST",
            subtitle = "Prove it.",
            trial_rule = "SURVIVE WITHOUT THE CHAIN",
            mode = "campaign",
            room_type = "trial",
            circle_id = "lust",
            hard_cut = true,
            completion = "survive",
            trial_timer = 12,
            removed_ability = "grapple",
            fragments_required = 0,
            show_gate = false,
            bg = { 0.24, 0.1, 0.17 },
            solid_color = { 0.44, 0.2, 0.29 },
            accent_color = { 0.97, 0.44, 0.58 },
            abilities = { shoot = true, grapple = false, dash = true },
            wind_areas = {
                {
                    x = 4 * 32, y = 1 * 32,
                    width = 14 * 32, height = 6 * 32,
                    force_x = 400,
                    label = "Tailwind",
                },
            },
            encounter_config = {
                trigger_x = 0,
                bounds = { left = 0, right = 22 * 32 },
                waves = {
                    {
                        spawns = {
                            { x = 16 * 32, y = 5 * 32, type = "walker" },
                            { x = 18 * 32, y = 2 * 32, type = "harpy" },
                        },
                        delay_after_clear = 0.4,
                    },
                    {
                        spawns = {
                            { x = 6 * 32, y = 5 * 32, type = "walker" },
                            { x = 14 * 32, y = 5 * 32, type = "walker" },
                            { x = 10 * 32, y = 2 * 32, type = "harpy" },
                            { x = 18 * 32, y = 2 * 32, type = "harpy" },
                        },
                    },
                },
            },
            map = {
                "111111111111111111111111",
                "1                      1",
                "1  P                   1",
                "1  11                  1",
                "1                      1",
                "1       11    11       1",
                "1                      1",
                "1   111          111   1",
                "111111111111111111111111",
            },
        },
    },
}
