return {
    id = "vertical_slice",
    title = "VERTICAL SLICE",
    subtitle = "Authored rooms, stable verbs, one meaningful loss.",
    rooms = {
        {
            id = "limbo_01",
            title = "LIMBO",
            subtitle = "Orientation. Learn the stable kit in a safe room.",
            mode = "campaign",
            room_type = "intro",
            checkpoint_id = "limbo-01",
            music_state = "limbo_intro",
            removed_ability = "none",
            environment_hook = "Stable traversal and fragments",
            transition_beat = "Virgil frames the climb through action, not speech.",
            bg = { 0.12, 0.14, 0.18 },
            solid_color = { 0.3, 0.34, 0.4 },
            accent_color = { 0.88, 0.58, 0.24 },
            gate_color = { 0.74, 0.74, 0.82 },
            locked_gate_color = { 0.34, 0.26, 0.28 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = true },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1   P                                    1",
                "1  111                                   1",
                "1                              C         1",
                "1                           11111        1",
                "1                                        1",
                "1          C                             1",
                "1        1111                            1",
                "1                           K            1",
                "1                        11111           1",
                "1                                        1",
                "1                                  C     G",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_02",
            title = "LIMBO",
            subtitle = "Traversal. Commit to jumps and wall recovery.",
            mode = "campaign",
            room_type = "teach",
            checkpoint_id = "limbo-02",
            music_state = "limbo_path",
            removed_ability = "none",
            environment_hook = "Safe platforming rehearsal",
            transition_beat = "The world stays honest while the player learns to trust it.",
            bg = { 0.12, 0.14, 0.18 },
            solid_color = { 0.3, 0.34, 0.4 },
            accent_color = { 0.88, 0.58, 0.24 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = true },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P                                     1",
                "1  11                                    1",
                "1             11111                      1",
                "1                                        1",
                "1                       11111            1",
                "1         C                              1",
                "1      11111                             1",
                "1                               C        1",
                "1                           11111        1",
                "1                                        1",
                "1                                      K G",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_03",
            title = "LIMBO",
            subtitle = "Combat. Shoot before pressure reaches the route.",
            mode = "campaign",
            room_type = "combat",
            checkpoint_id = "limbo-03",
            encounter_id = "first-walker-lane",
            music_state = "limbo_pressure",
            removed_ability = "none",
            environment_hook = "Enemy lanes on clean geometry",
            transition_beat = "Limbo proves violence is part of movement, not separate from it.",
            bg = { 0.12, 0.14, 0.18 },
            solid_color = { 0.3, 0.34, 0.4 },
            accent_color = { 0.88, 0.58, 0.24 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = true },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P                                     1",
                "1  11             E                      1",
                "1                1111                    1",
                "1                                        1",
                "1          C                             1",
                "1        11111                           1",
                "1                              H         1",
                "1                            1111        1",
                "1                                        1",
                "1                         C              1",
                "1                       11111          K G",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_04",
            title = "LIMBO",
            subtitle = "Grapple. Use anchors to skip dead air, not to trivialize choice.",
            mode = "campaign",
            room_type = "teach",
            checkpoint_id = "limbo-04",
            encounter_id = "grapple-room",
            music_state = "limbo_chain",
            removed_ability = "none",
            environment_hook = "Authored grapple anchors on readable jumps",
            transition_beat = "The chain is still a privilege here.",
            bg = { 0.12, 0.14, 0.18 },
            solid_color = { 0.3, 0.34, 0.4 },
            accent_color = { 0.88, 0.58, 0.24 },
            fragments_required = 1,
            abilities = { shoot = true, grapple = true },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1   P                           C        1",
                "1  111                        1111       1",
                "1                                        1",
                "1          11111                         1",
                "1                                        1",
                "1                        11111           1",
                "1                                        1",
                "1             K                          1",
                "1          11111                         1",
                "1                                        1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_05",
            title = "LIMBO",
            subtitle = "Gate exam. Clear pressure with the full verb set before the first loss.",
            mode = "campaign",
            room_type = "gate",
            checkpoint_id = "limbo-gate",
            encounter_id = "limbo-guardian",
            music_state = "limbo_gate",
            removed_ability = "none",
            environment_hook = "Full-kit exam",
            transition_beat = "The guardian watches what you depend on most.",
            bg = { 0.13, 0.15, 0.19 },
            solid_color = { 0.31, 0.35, 0.41 },
            accent_color = { 0.9, 0.6, 0.28 },
            fragments_required = 3,
            abilities = { shoot = true, grapple = true },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P                                     1",
                "1  11                H                   1",
                "1                   1111                 1",
                "1         C                              1",
                "1      11111                             1",
                "1                              E         1",
                "1                            1111        1",
                "1                 C                      1",
                "1              11111                     1",
                "1                                 C      1",
                "1                               11111  K G",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_01",
            title = "LUST",
            subtitle = "The chain is denied. Wind now decides the line.",
            mode = "campaign",
            room_type = "transition",
            checkpoint_id = "lust-01",
            music_state = "lust_intro",
            removed_ability = "grapple",
            environment_hook = "Wind lanes",
            transition_beat = "The guardian takes the chain. The air becomes the route.",
            bg = { 0.23, 0.11, 0.18 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            gate_color = { 0.96, 0.42, 0.58 },
            locked_gate_color = { 0.42, 0.16, 0.22 },
            fragments_required = 1,
            abilities = { shoot = true, grapple = false },
            wind_areas = {
                {
                    x = 9 * 32,
                    y = 2 * 32,
                    width = 7 * 32,
                    height = 6 * 32,
                    force_x = 460,
                    label = "Tailwind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P                                     1",
                "1  11                                    1",
                "1                                        1",
                "1                C                       1",
                "1              11111                     1",
                "1                                        1",
                "1                          K             1",
                "1                       11111            1",
                "1                                        1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_02",
            title = "LUST",
            subtitle = "Tailwinds turn long gaps into commitments.",
            mode = "campaign",
            room_type = "teach",
            checkpoint_id = "lust-02",
            music_state = "lust_wind",
            removed_ability = "grapple",
            environment_hook = "Commitment through momentum",
            transition_beat = "No recovery tool. Read the lane, then jump.",
            bg = { 0.23, 0.11, 0.18 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = false },
            wind_areas = {
                {
                    x = 5 * 32,
                    y = 2 * 32,
                    width = 9 * 32,
                    height = 6 * 32,
                    force_x = 420,
                    label = "Tailwind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1 P                                      1",
                "1 11                                     1",
                "1                                        1",
                "1          C                             1",
                "1        1111                            1",
                "1                                        1",
                "1                              C         1",
                "1                           1111         1",
                "1                   K                    1",
                "1                11111                   1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_03",
            title = "LUST",
            subtitle = "Crosswinds make combat timing matter again.",
            mode = "campaign",
            room_type = "combat",
            checkpoint_id = "lust-03",
            encounter_id = "wind-combat",
            music_state = "lust_pressure",
            removed_ability = "grapple",
            environment_hook = "Harpy pressure in unstable air",
            transition_beat = "The room pushes you while the enemy punishes hesitation.",
            bg = { 0.23, 0.11, 0.18 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = false },
            wind_areas = {
                {
                    x = 10 * 32,
                    y = 1 * 32,
                    width = 8 * 32,
                    height = 8 * 32,
                    force_x = -360,
                    label = "Crosswind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P                                     1",
                "1  11                           H        1",
                "1                               1111     1",
                "1         C                              1",
                "1      11111                             1",
                "1                   E                    1",
                "1                 1111                   1",
                "1                                C       1",
                "1                             11111      1",
                "1                        K               1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_04",
            title = "LUST",
            subtitle = "Hazards now demand momentum discipline.",
            mode = "campaign",
            room_type = "test",
            checkpoint_id = "lust-04",
            encounter_id = "hazard-lane",
            music_state = "lust_test",
            removed_ability = "grapple",
            environment_hook = "Wind over hazard lanes",
            transition_beat = "The room rewards clean commitment and punishes panic.",
            bg = { 0.23, 0.11, 0.18 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = false },
            wind_areas = {
                {
                    x = 7 * 32,
                    y = 1 * 32,
                    width = 10 * 32,
                    height = 8 * 32,
                    force_x = 410,
                    label = "Tailwind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P                                     1",
                "1  11                                    1",
                "1                                        1",
                "1             22                         1",
                "1       C    2222                        1",
                "1      111  222222          C            1",
                "1           2222222       1111           1",
                "1                                        1",
                "1                         K              1",
                "1                      11111             1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_05",
            title = "LUST",
            subtitle = "Final exam. No chain, no excuses, only the new rule.",
            mode = "campaign",
            room_type = "gate",
            checkpoint_id = "lust-gate",
            encounter_id = "lust-guardian",
            music_state = "lust_gate",
            removed_ability = "grapple",
            environment_hook = "Wind lanes plus enemy pressure",
            transition_beat = "What felt like theft now has to feel like mastery.",
            bg = { 0.24, 0.1, 0.17 },
            solid_color = { 0.44, 0.2, 0.29 },
            accent_color = { 0.97, 0.44, 0.58 },
            fragments_required = 3,
            abilities = { shoot = true, grapple = false },
            wind_areas = {
                {
                    x = 8 * 32,
                    y = 1 * 32,
                    width = 11 * 32,
                    height = 8 * 32,
                    force_x = 450,
                    label = "Tailwind",
                },
                {
                    x = 20 * 32,
                    y = 1 * 32,
                    width = 6 * 32,
                    height = 8 * 32,
                    force_x = -280,
                    label = "Crosswind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P                                     1",
                "1  11             H                      1",
                "1                  1111                  1",
                "1         C                              1",
                "1      11111                  E          1",
                "1                            1111        1",
                "1                 22                     1",
                "1      C         2222         C          1",
                "1    1111       222222      1111         1",
                "1                     K                  1",
                "1                                  C   G 1",
                "111111111111111111111111111111111111111111",
            },
        },
    },
}
