return {
    id = "vertical_slice",
    title = "VERTICAL SLICE",
    subtitle = "Authored rooms, stable verbs, one meaningful loss.",
    rooms = {
        {
            id = "limbo_01",
            title = "LIMBO",
            subtitle = "Orientation. Learn the stable kit in a safe room.",
            dramatic_question = "Can the player trust the climb before Hell starts cheating?",
            objective_text = "Collect the fragments, then enter the EXIT gate.",
            hud_objective_text = "Collect fragments. Exit right.",
            mode = "campaign",
            room_type = "intro",
            checkpoint_id = "limbo-01",
            music_state = "limbo_intro",
            removed_ability = "none",
            environment_hook = "Stable traversal and fragments",
            transition_beat = "Virgil frames the climb through action, not speech.",
            bg = { 0.12, 0.14, 0.18 },
            solid_color = { 0.3, 0.34, 0.4 },
            accent_color = { 0.88, 0.58, 0.24 },
            gate_color = { 0.74, 0.74, 0.82 },
            locked_gate_color = { 0.34, 0.26, 0.28 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = true },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "Take the fragments. Learn the climb before Hell starts bargaining.",
                    trigger_radius = 72,
                },
            },
            qa_expectations = {
                requires_encounter_clear = false,
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1   P V                                  1",
                "1  111                                   1",
                "1                              C         1",
                "1                           11111        1",
                "1                                        1",
                "1          C                             1",
                "1        1111                            1",
                "1                           K            1",
                "1                        11111           1",
                "1                                        1",
                "1                                  C     G",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_02",
            title = "LIMBO",
            subtitle = "Traversal. Commit to jumps and wall recovery.",
            dramatic_question = "Will the player trust stable geometry enough to commit cleanly?",
            objective_text = "Trust the stable lane, collect the fragments, then take the EXIT gate.",
            hud_objective_text = "Trust the lane. Collect. Exit right.",
            mode = "campaign",
            room_type = "teach",
            checkpoint_id = "limbo-02",
            music_state = "limbo_path",
            removed_ability = "none",
            environment_hook = "Safe platforming rehearsal",
            transition_beat = "The world stays honest while the player learns to trust it.",
            bg = { 0.12, 0.14, 0.18 },
            solid_color = { 0.3, 0.34, 0.4 },
            accent_color = { 0.88, 0.58, 0.24 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = true },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "Trust the wall, then commit. Doubt makes the gap longer.",
                    trigger_radius = 72,
                },
            },
            qa_expectations = {
                requires_encounter_clear = false,
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P V                                   1",
                "1  11                                    1",
                "1             11111                      1",
                "1                                        1",
                "1                       11111            1",
                "1         C                              1",
                "1      11111                             1",
                "1                               C        1",
                "1                           11111        1",
                "1                                        1",
                "1                                      K G",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_03",
            title = "LIMBO",
            subtitle = "Combat. Shoot before pressure reaches the route.",
            dramatic_question = "Can violence become part of movement instead of interrupting it?",
            objective_text = "Clear the pressure, collect the fragments, then take the EXIT gate.",
            hud_objective_text = "Clear pressure. Collect. Exit right.",
            mode = "campaign",
            room_type = "combat",
            checkpoint_id = "limbo-03",
            encounter_id = "first-walker-lane",
            music_state = "limbo_pressure",
            removed_ability = "none",
            environment_hook = "Enemy lanes on clean geometry",
            transition_beat = "Limbo proves violence is part of movement, not separate from it.",
            bg = { 0.12, 0.14, 0.18 },
            solid_color = { 0.3, 0.34, 0.4 },
            accent_color = { 0.88, 0.58, 0.24 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = true },
            qa_expectations = {
                requires_encounter_clear = true,
            },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "Hold the lane. If the route shakes, shoot first and move second.",
                    trigger_radius = 72,
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  PV                                    1",
                "1  11             E                      1",
                "1                1111                    1",
                "1                                        1",
                "1          C                             1",
                "1        11111                           1",
                "1                              H         1",
                "1                            1111        1",
                "1                                        1",
                "1                         C              1",
                "1                       11111          K G",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_04",
            title = "LIMBO",
            subtitle = "Grapple. Use anchors to skip dead air, not to trivialize choice.",
            dramatic_question = "Can the grapple feel like privilege rather than a crutch?",
            objective_text = "Use the anchors cleanly, collect the fragment, then reach the EXIT gate.",
            hud_objective_text = "Chain anchors. Collect. Exit right.",
            mode = "campaign",
            room_type = "teach",
            checkpoint_id = "limbo-04",
            encounter_id = "grapple-room",
            music_state = "limbo_chain",
            removed_ability = "none",
            environment_hook = "Authored grapple anchors on readable jumps",
            transition_beat = "The chain is still a privilege here.",
            bg = { 0.12, 0.14, 0.18 },
            solid_color = { 0.3, 0.34, 0.4 },
            accent_color = { 0.88, 0.58, 0.24 },
            fragments_required = 1,
            abilities = { shoot = true, grapple = true },
            qa_expectations = {
                requires_encounter_clear = false,
                requires_environment_label = false,
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1   P                           C        1",
                "1  111                        1111       1",
                "1                                        1",
                "1          11111               A         1",
                "1                                        1",
                "1                        11111     A     1",
                "1                                        1",
                "1             K                          1",
                "1          11111                         1",
                "1                                        1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "limbo_05",
            title = "LIMBO",
            subtitle = "Gate exam. Clear pressure with the full verb set before the first loss.",
            dramatic_question = "What part of the full kit does the player rely on most?",
            objective_text = "Clear the guardian trial, collect the fragments, then take the EXIT gate.",
            hud_objective_text = "Clear the trial. Collect. Exit right.",
            mode = "campaign",
            room_type = "gate",
            checkpoint_id = "limbo-gate",
            encounter_id = "limbo-guardian",
            music_state = "limbo_gate",
            removed_ability = "none",
            environment_hook = "Full-kit exam",
            transition_beat = "The guardian watches what you depend on most.",
            bg = { 0.13, 0.15, 0.19 },
            solid_color = { 0.31, 0.35, 0.41 },
            accent_color = { 0.9, 0.6, 0.28 },
            fragments_required = 3,
            abilities = { shoot = true, grapple = true },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "This room is a verdict. Whatever you lean on most will be the next thing Hell strips away.",
                    trigger_radius = 72,
                },
            },
            qa_expectations = {
                requires_encounter_clear = true,
            },
            encounter_config = {
                trigger_x = 15 * 32,
                bounds = {
                    left = 4 * 32,
                    right = 37 * 32,
                },
                intro_title = "LIMBO GUARDIAN",
                intro_subtitle = "Full kit. Clear every wave before the gate yields.",
                outro_subtitle = "The guardian relents. The chain will not survive the next threshold.",
                waves = {
                    {
                        banner = "WAVE 1",
                        subtitle = "Pressure from above. Keep moving and shoot on rhythm.",
                        spawns = {
                            { x = 24 * 32, y = 7 * 32, type = "walker" },
                            { x = 30 * 32, y = 3 * 32, type = "harpy" },
                        },
                        delay_after_clear = 0.55,
                    },
                    {
                        banner = "WAVE 2",
                        subtitle = "Use the full kit. The lane asks for chain confidence.",
                        spawns = {
                            { x = 16 * 32, y = 9 * 32, type = "walker" },
                            { x = 26 * 32, y = 6 * 32, type = "walker" },
                            { x = 33 * 32, y = 2 * 32, type = "harpy" },
                        },
                    },
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  PV                                    1",
                "1  11                     A              1",
                "1                 1111                   1",
                "1         C                              1",
                "1      11111                 A           1",
                "1                           1111         1",
                "1                                        1",
                "1                 C                      1",
                "1              11111              A      1",
                "1                                 C      1",
                "1                               11111  K G",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_01",
            title = "LUST",
            subtitle = "The chain is denied. Wind now decides the line.",
            dramatic_question = "Does the loss of the chain force a new way of reading the room?",
            objective_text = "Feel the loss, ride the wind, collect the fragment, then take the EXIT gate.",
            hud_objective_text = "Feel the loss. Read the wind. Exit right.",
            mode = "campaign",
            room_type = "transition",
            checkpoint_id = "lust-01",
            music_state = "lust_intro",
            removed_ability = "grapple",
            environment_hook = "Wind lanes",
            transition_beat = "The guardian takes the chain. The air becomes the route.",
            bg = { 0.23, 0.11, 0.18 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            gate_color = { 0.96, 0.42, 0.58 },
            locked_gate_color = { 0.42, 0.16, 0.22 },
            fragments_required = 1,
            abilities = { shoot = true, grapple = false },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "Do not reach for the missing chain. Read the air before you spend yourself into it.",
                    trigger_radius = 72,
                },
            },
            qa_expectations = {
                requires_removed_ability_notice = true,
                requires_environment_label = true,
            },
            beat_config = {
                trigger_x = 8 * 32,
                title = "THE CHAIN IS TAKEN",
                subtitle = "Wind replaces recovery. Read the lane before you commit.",
                duration = 2.4,
                shake = 4,
            },
            wind_areas = {
                {
                    x = 6 * 32,
                    y = 2 * 32,
                    width = 9 * 32,
                    height = 6 * 32,
                    force_x = 460,
                    label = "Tailwind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  PV                                    1",
                "1  11                                    1",
                "1                                        1",
                "1                C                       1",
                "1              11111                     1",
                "1                                        1",
                "1                          K             1",
                "1                       11111            1",
                "1                                        1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_02",
            title = "LUST",
            subtitle = "Tailwinds turn long gaps into commitments. Lower your profile before you spend it.",
            dramatic_question = "Can posture replace the recovery the grapple used to provide?",
            objective_text = "Brace low into the gust, then roll your momentum into the EXIT gate.",
            hud_objective_text = "Brace low. Roll through. Exit right.",
            mode = "campaign",
            room_type = "teach",
            checkpoint_id = "lust-02",
            music_state = "lust_wind",
            removed_ability = "grapple",
            environment_hook = "Commitment through momentum and posture",
            transition_beat = "No recovery tool. Brace before the gust, then commit through it.",
            bg = { 0.23, 0.11, 0.18 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = false, crouch = true, roll = true },
            qa_expectations = {
                requires_removed_ability_notice = true,
                requires_environment_label = true,
            },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "Get low when the gust swells. Roll only when the line is yours.",
                    trigger_radius = 72,
                },
            },
            wind_areas = {
                {
                    x = 5 * 32,
                    y = 2 * 32,
                    width = 9 * 32,
                    height = 6 * 32,
                    force_x = 500,
                    label = "Tailwind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1 P V                                    1",
                "1 11                                     1",
                "1                                        1",
                "1          C                             1",
                "1        1111                            1",
                "1                                        1",
                "1                              C         1",
                "1                           1111         1",
                "1                   K                    1",
                "1                11111                   1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_03",
            title = "LUST",
            subtitle = "Crosswinds make combat timing matter again.",
            dramatic_question = "Can the player keep control when the room bends both movement and fire?",
            objective_text = "Hold the lane through the crosswind, clear the pressure, then take the EXIT gate.",
            hud_objective_text = "Hold the lane. Clear pressure. Exit right.",
            mode = "campaign",
            room_type = "combat",
            checkpoint_id = "lust-03",
            encounter_id = "wind-combat",
            music_state = "lust_pressure",
            removed_ability = "grapple",
            environment_hook = "Harpy pressure in unstable air",
            transition_beat = "The room pushes you while the enemy punishes hesitation.",
            bg = { 0.23, 0.11, 0.18 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = false },
            qa_expectations = {
                requires_environment_label = true,
            },
            beat_config = {
                trigger_x = 8 * 32,
                title = "CROSSWIND PUNISH",
                subtitle = "The air lies sideways now. Bank the shot when the lane refuses a straight line.",
                duration = 2.1,
                shake = 3,
            },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "Do not race the gust. Let the wall finish the shot the wind bends away.",
                    trigger_radius = 72,
                },
            },
            wind_areas = {
                {
                    x = 10 * 32,
                    y = 1 * 32,
                    width = 8 * 32,
                    height = 8 * 32,
                    force_x = -360,
                    label = "Crosswind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P V                                   1",
                "1  11                           H        1",
                "1                               1111     1",
                "1         C                              1",
                "1      11111                             1",
                "1                   E                    1",
                "1                 1111                   1",
                "1                                C       1",
                "1                             11111      1",
                "1                        K               1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_04",
            title = "LUST",
            subtitle = "Hazards now demand momentum discipline.",
            dramatic_question = "Will the player spend the wind cleanly, or panic into the hazard lanes?",
            objective_text = "Take the tailwind cleanly, cross the hazard lanes, then reach the EXIT gate.",
            hud_objective_text = "Take the push. Cross hazards. Exit right.",
            mode = "campaign",
            room_type = "test",
            checkpoint_id = "lust-04",
            encounter_id = "hazard-lane",
            music_state = "lust_test",
            removed_ability = "grapple",
            environment_hook = "Wind over hazard lanes",
            transition_beat = "The room rewards clean commitment and punishes panic.",
            bg = { 0.23, 0.11, 0.18 },
            solid_color = { 0.42, 0.2, 0.28 },
            accent_color = { 0.95, 0.46, 0.56 },
            fragments_required = 2,
            abilities = { shoot = true, grapple = false },
            qa_expectations = {
                requires_environment_label = true,
            },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "Take the push only once. Even the stone will return your fire if the lane turns mean.",
                    trigger_radius = 72,
                },
            },
            wind_areas = {
                {
                    x = 7 * 32,
                    y = 1 * 32,
                    width = 10 * 32,
                    height = 8 * 32,
                    force_x = 410,
                    label = "Tailwind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  P V                                   1",
                "1  11                                    1",
                "1                                        1",
                "1             22                         1",
                "1       C    2222                        1",
                "1      111  222222          C            1",
                "1           2222222       1111           1",
                "1                                        1",
                "1                         K              1",
                "1                      11111             1",
                "1                                      G 1",
                "111111111111111111111111111111111111111111",
            },
        },
        {
            id = "circle1_05",
            title = "LUST",
            subtitle = "Final exam. No chain, no excuses, only the new rule.",
            dramatic_question = "Has the theft of the chain become a new mastery instead of a complaint?",
            objective_text = "Clear the guardian trial under wind pressure, then take the EXIT gate.",
            hud_objective_text = "Clear the trial. Hold the wind. Exit right.",
            mode = "campaign",
            room_type = "gate",
            checkpoint_id = "lust-gate",
            encounter_id = "lust-guardian",
            music_state = "lust_gate",
            removed_ability = "grapple",
            environment_hook = "Wind lanes plus enemy pressure",
            transition_beat = "What felt like theft now has to feel like mastery.",
            bg = { 0.24, 0.1, 0.17 },
            solid_color = { 0.44, 0.2, 0.29 },
            accent_color = { 0.97, 0.44, 0.58 },
            fragments_required = 3,
            abilities = { shoot = true, grapple = false },
            npc_guidance = {
                {
                    speaker = "Virgil",
                    line = "If the new rule is real, prove it here. No chain. No apology. Just the line you can still hold.",
                    trigger_radius = 72,
                },
            },
            qa_expectations = {
                requires_encounter_clear = true,
                requires_removed_ability_notice = true,
                requires_environment_label = true,
            },
            encounter_config = {
                trigger_x = 14 * 32,
                bounds = {
                    left = 4 * 32,
                    right = 38 * 32,
                },
                intro_title = "LUST GUARDIAN",
                intro_subtitle = "No chain. Hold the lane while the wind rewrites the route.",
                outro_subtitle = "The new rule holds. The gate opens to the next descent.",
                waves = {
                    {
                        banner = "WAVE 1",
                        subtitle = "Tailwind pressure. Hold your fire until the lane opens.",
                        spawns = {
                            { x = 24 * 32, y = 6 * 32, type = "walker" },
                            { x = 30 * 32, y = 3 * 32, type = "harpy" },
                        },
                        delay_after_clear = 0.55,
                    },
                    {
                        banner = "WAVE 2",
                        subtitle = "Crosswind punish. No chain means no bailout.",
                        spawns = {
                            { x = 18 * 32, y = 9 * 32, type = "walker" },
                            { x = 26 * 32, y = 6 * 32, type = "walker" },
                            { x = 33 * 32, y = 3 * 32, type = "harpy" },
                        },
                    },
                },
            },
            wind_areas = {
                {
                    x = 8 * 32,
                    y = 1 * 32,
                    width = 11 * 32,
                    height = 8 * 32,
                    force_x = 450,
                    label = "Tailwind",
                },
                {
                    x = 20 * 32,
                    y = 1 * 32,
                    width = 6 * 32,
                    height = 8 * 32,
                    force_x = -280,
                    label = "Crosswind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111",
                "1                                        1",
                "1  PV                                    1",
                "1  11                                    1",
                "1                  1111                  1",
                "1         C                              1",
                "1      11111                  22         1",
                "1                            2222        1",
                "1                 22                     1",
                "1      C         2222         C          1",
                "1    1111       222222      1111         1",
                "1                     K                  1",
                "1                                  C   G 1",
                "111111111111111111111111111111111111111111",
            },
        },
    },
}
