return {
    id = "proving_ground",
    title = "PROVING GROUND",
    subtitle = "Tune movement, combat, damage, and restart speed.",
    rooms = {
        {
            id = "prove_traversal",
            title = "PROVING GROUND",
            subtitle = "Traversal lane. Tune run-up, jump buffer, and one clean grapple commitment.",
            recovery_hint = "Jump once, then latch early. The anchor is the correction, not the bailout.",
            transition_beat = "The route should read in one glance, then reward one clean commitment.",
            objective_text = "Commit to the lane, latch one clean grapple, then enter the EXIT gate.",
            hud_objective_text = "Commit, latch, exit right.",
            mode = "proving_ground",
            room_type = "traversal",
            checkpoint_id = "prove-traversal",
            music_state = "prove_traversal",
            show_gate = true,
            fragments_required = 0,
            bg = { 0.08, 0.09, 0.11 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.92, 0.55, 0.18 },
            hazard_color = { 0.88, 0.22, 0.2 },
            sludge_color = { 0.32, 0.48, 0.24 },
            abilities = { shoot = true, grapple = true },
            qa_expectations = {
                required_result = "movement_complete",
                max_deaths = 0,
                min_grapple_latches = 1,
                min_distance = 650,
            },
            map = {
                "111111111111111111111111111111111111111111111111",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1                  A                           1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1   P                                      G   1",
                "1  111111111111            1111111111111111    1",
                "1                                       K      1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "111111111111111111111111111111111111111111111111",
            },
        },
        {
            id = "prove_combat",
            title = "PROVING GROUND",
            subtitle = "Combat lane. Tune shot rhythm, feedback, and restart speed.",
            recovery_hint = "If the lane clogs, stop drifting and retake rhythm with one clean shot at a time.",
            transition_beat = "Violence should feel like movement pressure, not a separate mode.",
            objective_text = "Clear the lane fast, then enter the EXIT gate.",
            hud_objective_text = "Clear the lane. Exit right.",
            mode = "proving_ground",
            room_type = "combat",
            checkpoint_id = "prove-combat",
            encounter_id = "prove-combat",
            music_state = "prove_combat",
            show_gate = true,
            fragments_required = 0,
            bg = { 0.08, 0.09, 0.11 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.92, 0.55, 0.18 },
            hazard_color = { 0.88, 0.22, 0.2 },
            sludge_color = { 0.32, 0.48, 0.24 },
            abilities = { shoot = true, grapple = true },
            encounter_config = {
                trigger_x = 10 * 32,
                bounds = {
                    left = 4 * 32,
                    right = 43 * 32,
                },
                intro_title = "COMBAT RHYTHM",
                intro_subtitle = "Clear the pressure before the gate yields.",
                outro_subtitle = "Lane clear. Keep moving.",
                waves = {
                    {
                        banner = "WAVE 1",
                        subtitle = "Shoot on rhythm while holding the line.",
                        spawns = {
                            { x = 18 * 32, y = 6 * 32, type = "walker" },
                            { x = 25 * 32, y = 6 * 32, type = "walker" },
                            { x = 33 * 32, y = 6 * 32, type = "walker" },
                        },
                    },
                },
            },
            qa_expectations = {
                required_result = "combat_complete",
                max_deaths = 0,
                min_shots_hit = 2,
                min_accuracy = 50,
                requires_encounter_clear = true,
            },
            map = {
                "111111111111111111111111111111111111111111111111",
                "1                                              1",
                "1   P                                          1",
                "1                                           G  1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1                                    K         1",
                "1                                              1",
                "1                                              1",
                "1 1111111111111111111111111111111111111111111  1",
                "111111111111111111111111111111111111111111111111",
            },
        },
        {
            id = "prove_ricochet",
            title = "PROVING GROUND",
            subtitle = "Ricochet lane. Bank the shot over hard cover, then finish the route clean.",
            recovery_hint = "Hold the firing mark, hit the wall first, then move only after the bank kill lands.",
            transition_beat = "If the straight line is denied, the wall should become part of the weapon.",
            objective_text = "Bank the shot over the cover, kill the threat, then enter the EXIT gate.",
            hud_objective_text = "Bank the shot. Kill. Exit right.",
            mode = "proving_ground",
            room_type = "ricochet",
            checkpoint_id = "prove-ricochet",
            music_state = "prove_ricochet",
            show_gate = true,
            fragments_required = 0,
            bg = { 0.08, 0.09, 0.11 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.92, 0.55, 0.18 },
            hazard_color = { 0.88, 0.22, 0.2 },
            sludge_color = { 0.32, 0.48, 0.24 },
            weapon_profile = {
                ricochets = 1,
                auto_aim = false,
            },
            abilities = { shoot = true, grapple = true },
            qa_expectations = {
                required_result = "ricochet_complete",
                max_deaths = 0,
                min_shots_hit = 1,
                min_shot_ricochets = 1,
                min_bank_kills = 1,
                min_distance = 700,
            },
            map = {
                "111111111111111111111111111111111111111111111111",
                "1             111                              1",
                "1             111                              1",
                "1               E                       G      1",
                "1              111                             1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1   P                                     K    1",
                "1" .. string.rep("1", 46) .. "1",
                "1                                              1",
                "1                                              1",
                "111111111111111111111111111111111111111111111111",
            },
        },
        {
            id = "prove_grapple",
            title = "PROVING GROUND",
            subtitle = "Grapple lane. Chain multiple anchors before the exit yields.",
            recovery_hint = "Missed the first latch? Re-center forward and throw again before the dead air wins.",
            transition_beat = "Dead air should disappear once the anchor route reads.",
            objective_text = "Chain the anchors cleanly, then hit the EXIT gate.",
            hud_objective_text = "Chain anchors. Exit right.",
            mode = "proving_ground",
            room_type = "grapple",
            checkpoint_id = "prove-grapple",
            music_state = "prove_grapple",
            show_gate = true,
            fragments_required = 0,
            bg = { 0.08, 0.09, 0.11 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.92, 0.55, 0.18 },
            hazard_color = { 0.88, 0.22, 0.2 },
            sludge_color = { 0.32, 0.48, 0.24 },
            abilities = { shoot = true, grapple = true },
            qa_expectations = {
                required_result = "grapple_complete",
                max_deaths = 0,
                min_grapple_latches = 2,
                min_distance = 1200,
            },
            map = {
                "111111111111111111111111111111111111111111111111",
                "1                                              1",
                "1  P                                           1",
                "1                 A               A            1",
                "1                                              1",
                "1                                              1",
                "1                              A               1",
                "1                                              1",
                "1  11111      22222222      111111      22222221",
                "1      K                                      G1",
                "1             11111111               11111111111",
                "1                                              1",
                "1                                              1",
                "111111111111111111111111111111111111111111111111",
            },
        },
        {
            id = "prove_dash",
            title = "PROVING GROUND",
            subtitle = "Dash lane. Burst through the choke, land clean, then vault the exit wall.",
            recovery_hint = "Do not panic-dash. Walk into the choke, spend one burst, then jump the finish wall.",
            transition_beat = "Dash should feel like a committed throw, not a panic button.",
            objective_text = "Drive into the choke, dash the hazard channel, then vault into the EXIT gate.",
            hud_objective_text = "Hit the choke. Dash through. Exit right.",
            mode = "proving_ground",
            room_type = "dash",
            checkpoint_id = "prove-dash",
            music_state = "prove_dash",
            show_gate = true,
            fragments_required = 0,
            bg = { 0.08, 0.09, 0.11 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.92, 0.55, 0.18 },
            hazard_color = { 0.88, 0.22, 0.2 },
            sludge_color = { 0.32, 0.48, 0.24 },
            abilities = { shoot = true, grapple = true, dash = true },
            qa_expectations = {
                required_result = "dash_complete",
                max_deaths = 0,
                min_dashes = 1,
                min_distance = 900,
            },
            map = {
                "111111111111111111111111111111111111111111111111",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1" .. string.rep(" ", 39) .. "G" .. string.rep(" ", 6) .. "1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1" .. string.rep(" ", 31) .. string.rep("1", 9) .. string.rep(" ", 6) .. "1",
                "1" .. string.rep(" ", 15) .. string.rep("1", 9) .. string.rep(" ", 22) .. "1",
                "1" .. "   P" .. string.rep(" ", 28) .. "K" .. string.rep(" ", 4) .. "111" .. string.rep(" ", 6) .. "1",
                "1" .. string.rep("1", 16) .. string.rep("2", 3) .. string.rep("1", 17) .. string.rep(" ", 10) .. "1",
                "1                                              1",
                "1                                              1",
                "111111111111111111111111111111111111111111111111",
            },
        },
        {
            id = "prove_pressure",
            title = "PROVING GROUND",
            subtitle = "Mixed pressure. Clear grounded threats while crossing hazard lanes.",
            recovery_hint = "When pressure stacks, stabilize the lane first. Movement only matters after the threats thin.",
            transition_beat = "The room should ask for traversal commitment under clean pressure.",
            objective_text = "Clear the threats while crossing the hazards, then take the EXIT gate.",
            hud_objective_text = "Clear pressure. Cross. Exit right.",
            mode = "proving_ground",
            room_type = "pressure",
            checkpoint_id = "prove-pressure",
            encounter_id = "prove-pressure",
            music_state = "prove_pressure",
            show_gate = true,
            fragments_required = 0,
            bg = { 0.08, 0.09, 0.11 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.92, 0.55, 0.18 },
            hazard_color = { 0.88, 0.22, 0.2 },
            sludge_color = { 0.32, 0.48, 0.24 },
            abilities = { shoot = true, grapple = true },
            encounter_config = {
                trigger_x = 10 * 32,
                bounds = {
                    left = 4 * 32,
                    right = 43 * 32,
                },
                intro_title = "PRESSURE LANE",
                intro_subtitle = "Keep moving. Clear the threats before the route opens.",
                outro_subtitle = "Pressure held. Finish the room.",
                waves = {
                    {
                        banner = "WAVE 1",
                        subtitle = "Cross the hazard lanes without losing the rhythm.",
                        spawns = {
                            { x = 22 * 32, y = 6 * 32, type = "walker" },
                            { x = 34 * 32, y = 10 * 32, type = "walker" },
                        },
                    },
                },
            },
            qa_expectations = {
                required_result = "pressure_complete",
                max_deaths = 0,
                min_shots_hit = 1,
                min_distance = 700,
                requires_encounter_clear = true,
            },
            wind_areas = {
                {
                    x = 16 * 32,
                    y = 1 * 32,
                    width = 7 * 32,
                    height = 7 * 32,
                    force_x = 300,
                    label = "Drift",
                },
            },
            map = {
                "111111111111111111111111111111111111111111111111",
                "1                                              1",
                "1   P                                          1",
                "1  111                                         1",
                "1                                           G  1",
                "1           22                                 1",
                "1          2222            E                   1",
                "1         222222         11111                1",
                "1                                              1",
                "1                         22                   1",
                "1                        2222      E           1",
                "1                       222222   11111   K     1",
                "1                                              1",
                "1                                              1",
                "111111111111111111111111111111111111111111111111",
            },
        },
        {
            id = "prove_posture",
            title = "PROVING GROUND",
            subtitle = "Posture lane. Brace into the gust, then roll through the committed line.",
            recovery_hint = "Crouch buys control. Roll only after the gust lines you up with the gap.",
            transition_beat = "Low profile should buy control. Roll should cash that control into motion.",
            objective_text = "Brace into the wind, roll the hazard break, then take the EXIT gate.",
            hud_objective_text = "Brace low. Roll through. Exit right.",
            mode = "proving_ground",
            room_type = "posture",
            checkpoint_id = "prove-posture",
            music_state = "prove_posture",
            show_gate = true,
            fragments_required = 0,
            bg = { 0.08, 0.09, 0.11 },
            solid_color = { 0.28, 0.31, 0.36 },
            accent_color = { 0.92, 0.55, 0.18 },
            hazard_color = { 0.88, 0.22, 0.2 },
            sludge_color = { 0.32, 0.48, 0.24 },
            abilities = { shoot = true, grapple = true, dash = true, crouch = true, roll = true },
            qa_expectations = {
                required_result = "posture_complete",
                max_deaths = 0,
                min_rolls = 1,
                min_crouch_time = 0.3,
                min_distance = 780,
                requires_environment_label = true,
            },
            wind_areas = {
                {
                    x = 4 * 32,
                    y = 8 * 32,
                    width = 14 * 32,
                    height = 4 * 32,
                    force_x = -560,
                    label = "Headwind",
                },
            },
            map = {
                "111111111111111111111111111111111111111111111111",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "1                                        G     1",
                "1                                              1",
                "1                     11111                    1",
                "1                                              1",
                "1                                              1",
                "1   P                                          1",
                "1  11111111111111111   2222   11111111111111K  1",
                "1                                              1",
                "1                                              1",
                "1                                              1",
                "111111111111111111111111111111111111111111111111",
            },
        },
    },
}
